source "https://supermarket.getchef.com"

cookbook "mysql"
cookbook "nginx"
cookbook "php"
cookbook "composer"
cookbook "php-fpm"
cookbook "php-mcrypt"
cookbook "nodejs"
cookbook "npm"
cookbook "redisio"
cookbook "ruby"
cookbook "mysettings", path: "site-cookbooks/mysettings"
